[versions]

compileSdk = "33"
targetSdk = "33"
minSdk = "23"

kotlin-lang = "1.7.20"
kotlin-dokka = "1.7.20"
androidGradlePlugin = "7.3.1"
mavenPublish = "0.22.0"

kotlin-serialization = "1.4.1"
android-sdkCommon = "30.3.1"
android-lint = "30.3.1"
androidx-activityCompose = "1.6.1"
androidx-activityComposeCatalog = "1.6.1"
androidx-core = "1.9.0"
androidx-constraint-layout = "1.0.1"
accompanist-main = "0.28.0"
coil = "2.2.2"
compose-compiler = "1.3.2"
square-kotlinPoet = "1.12.0"

[libraries]

kotlin-dokka = { module = "org.jetbrains.dokka:dokka-base", version.ref = "kotlin-dokka" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-lang" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
android-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-sdkCommon" }
android-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-lint" }
android-lint-impl = { module = "com.android.tools.lint:lint", version.ref = "android-lint" }
android-lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-lint" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-activityComposeCatalog = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityComposeCatalog" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraint-layout" }
androidx-customView = { module = "androidx.customview:customview", version = "1.1.0" }
androidx-customViewPoolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.0.0" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-main" }
accompanist-systemController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-main" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-animation = { module = "androidx.compose.animation:animation", version = "1.3.2" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics", version = "1.3.1" }
# compiler dependency is defined to help Renovabot update the version
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version = "1.3.1" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version = "1.3.1" }
compose-material = { module = "androidx.compose.material:material", version = "1.3.1" }
compose-materialRipple = { module = "androidx.compose.material:material-ripple", version = "1.3.1" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version = "1.3.1" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version = "1.3.2" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version = "1.3.2" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version = "1.3.1" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.3.1" }
compose-test = { module = "androidx.compose.ui:ui-test", version = "1.3.1" }
compose-ui = { module = "androidx.compose.ui:ui", version = "1.3.2" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version = "1.3.2" }
compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version = "1.3.2" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util", version = "1.3.2" }
compose-viewBinding = { module = "androidx.compose.ui:ui-viewbinding", version = "1.3.1" }
javaJq = { module = "net.thisptr:jackson-jq", version="1.0.0-preview.20220705" }
junit = { module = "junit:junit", version = "4.13.2" }
kiwi-navigationComposeTyped = { module = "com.kiwi.navigation-compose.typed:core", version = "0.4.0" }
square-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "square-kotlinPoet" }

[bundles]

[plugins]
agp-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
agp-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-lang" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-lang" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-lang" }
mavenPublish = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
paparazzi = { id = "dev.chrisbanes.paparazzi", version = "1.1.0-sdk33-alpha02" }
appDistribution = { id = "com.google.firebase.appdistribution", version = "3.1.1" }
