[versions]

compileSdk = "32"
minSdk = "23"

kotlin-lang = "1.7.0"
kotlin-dokka = "1.7.0"
android-gradle-plugin = "7.3.0-beta05"
maven-publish = "0.21.0"

kotlin-serialization = "1.3.3"
android-sdkCommon = "30.2.1"
android-lint = "30.2.1"
androidx-activityCompose = "1.4.0"
androidx-core = "1.8.0"
androidx-constraint-layout = "1.0.1"
accompanist-main = "0.24.13-rc"
coil = "2.0.0"
compose-compiler = "1.2.0"
compose-main = "1.2.0"
compose-navigation = "2.5.0"
square-kotlinPoet = "1.12.0"

[libraries]

kotlin-dokka = { module = "org.jetbrains.dokka:dokka-base", version.ref = "kotlin-dokka" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-lang" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
android-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-sdkCommon" }
android-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-lint" }
android-lint-impl = { module = "com.android.tools.lint:lint", version.ref = "android-lint" }
android-lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-lint" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraint-layout" }
androidx-customView = { module = "androidx.customview:customview", version = "1.1.0" }
androidx-customViewPoolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.0.0-rc01" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-main" }
accompanist-systemController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-main" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-main" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose-main" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-main" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-main" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-main" }
compose-materialRipple = { module = "androidx.compose.material:material-ripple", version.ref = "compose-main" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-main" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-main" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-main" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-main" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-main" }
compose-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose-main" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-main" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-main" }
compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-main" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "compose-main" }
compose-viewBinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose-main" }
junit = { module = "junit:junit", version = "4.13.2" }
square-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "square-kotlinPoet" }

[bundles]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.11.1" }
paparazzi = { id = "app.cash.paparazzi", version = "1.0.0" }
