[versions]

compileSdk = "34"
targetSdk = "33"
minSdk = "23"

kotlin-lang = "1.9.0"
kotlin-dokka = "1.8.20"

kotlin-serialization = "1.5.1"
android-sdkCommon = "31.1.0"
android-lint = "31.1.0-rc01"
androidx-activityCompose = "1.7.2"
androidx-activityComposeCatalog = "1.7.2"
androidx-core = "1.10.1"
androidx-constraint-layout = "1.0.1"
compose-compiler = "1.5.1"
mockk = "1.13.7"
square-kotlinPoet = "1.14.2"

[libraries]

kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
kotlin-dokka = { module = "org.jetbrains.dokka:dokka-base", version.ref = "kotlin-dokka" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-lang" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
android-desugarJdk = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }
android-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-sdkCommon" }
android-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-lint" }
android-lint-impl = { module = "com.android.tools.lint:lint", version.ref = "android-lint" }
android-lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-lint" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-activityComposeCatalog = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityComposeCatalog" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraint-layout" }
androidx-customView = { module = "androidx.customview:customview", version = "1.1.0" }
androidx-customViewPoolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.0.0" }
accompanist-systemController = "com.google.accompanist:accompanist-systemuicontroller:0.30.1"
coil = { module = "io.coil-kt:coil-compose", version = "2.4.0" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics" }
compose-bom = "dev.chrisbanes.compose:compose-bom:2023.04.00-beta02"
# compiler dependency is defined to help Renovabot update the version
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = "androidx.compose.material3:material3:1.1.1"
compose-materialRipple = { module = "androidx.compose.material:material-ripple" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.7.0" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-test = { module = "androidx.compose.ui:ui-test" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4" }
compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util" }
compose-viewBinding = { module = "androidx.compose.ui:ui-viewbinding" }
hamcrest = { module = "org.hamcrest:hamcrest-all", version = "1.3" }
javaJq = { module = "net.thisptr:jackson-jq", version = "1.0.0-preview.20230409" }
junit = { module = "junit:junit", version = "4.13.2" }
kiwi-navigationComposeTyped = { module = "com.kiwi.navigation-compose.typed:core", version = "0.6.2" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version = "4.10.3" }
slack-composeLintChecks = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.2.0" }
square-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "square-kotlinPoet" }

[bundles]
