name: Design Tokens Updater

on:
  schedule:
    - cron: '0 4 * * 1-5' # every work-day at 6:00am in +02:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Install pngquant
        run: sudo apt-get install -y pngquant
      - name: Today env
        run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Update Tokens
        run: bash .github/tokens-updater.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PRBOT_APP_ID }}
          private_key: ${{ secrets.PRBOT_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            feature
            design-tokens-autoupdate
          title: Design Tokens Update on ${{ env.TODAY }}
          body: ""
          base: main
          branch: tokens-autoupdate
